language: android
dist: trusty
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-30.0.2

    # The SDK version used to compile your project
    - android-30

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository